version: "3"

services:
  fief-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cybroid:latest
    command: fief run-server
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"  # Expose Fief server port to the host

  fief-worker:
    image: cybroid:latest
    command: fief run-worker -p 1 -t 1
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=fief
      - POSTGRES_USER=fief
      - POSTGRES_DB=fief
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data: